// Copyright Citra Emulator Project / Azahar Emulator Project
// Licensed under GPLv2 or any later version
// Refer to the license.txt file included.

#pragma once

#include <boost/hana/string.hpp>


namespace Settings {

namespace Keys {
#define DEFINE_KEY(KEY) static constexpr char KEY[] = #KEY;


DEFINE_KEY(use_artic_base_controller)
DEFINE_KEY(enable_gamemode)
DEFINE_KEY(use_cpu_jit)
DEFINE_KEY(cpu_clock_percentage)
DEFINE_KEY(is_new_3ds)
DEFINE_KEY(lle_applets)
DEFINE_KEY(deterministic_async_operations)
DEFINE_KEY(enable_required_online_lle_modules)
DEFINE_KEY(use_virtual_sd)
DEFINE_KEY(use_custom_storage)
DEFINE_KEY(compress_cia_installs)
DEFINE_KEY(async_fs_operations)
DEFINE_KEY(region_value)
DEFINE_KEY(init_clock)
DEFINE_KEY(init_time)
DEFINE_KEY(init_time_offset)
DEFINE_KEY(init_ticks_type)
DEFINE_KEY(init_ticks_override)
DEFINE_KEY(plugin_loader)
DEFINE_KEY(allow_plugin_loader)
DEFINE_KEY(steps_per_hour)
DEFINE_KEY(apply_region_free_patch)
DEFINE_KEY(graphics_api)
DEFINE_KEY(physical_device)
DEFINE_KEY(use_gles)
DEFINE_KEY(renderer_debug)
DEFINE_KEY(pica_debugging)
DEFINE_KEY(dump_command_buffers)
DEFINE_KEY(spirv_shader_gen)
DEFINE_KEY(disable_spirv_optimizer)
DEFINE_KEY(async_shader_compilation)
DEFINE_KEY(async_presentation)
DEFINE_KEY(use_hw_shader)
DEFINE_KEY(use_disk_shader_cache)
DEFINE_KEY(shaders_accurate_mul)
DEFINE_KEY(use_vsync)
DEFINE_KEY(use_skip_duplicate_frames)
DEFINE_KEY(use_display_refresh_rate_detection)
DEFINE_KEY(use_shader_jit)
DEFINE_KEY(resolution_factor)
DEFINE_KEY(frame_limit)
DEFINE_KEY(turbo_limit)
DEFINE_KEY(texture_filter)
DEFINE_KEY(texture_sampling)
DEFINE_KEY(delay_game_render_thread_us)
DEFINE_KEY(simulate_3ds_gpu_timings)
DEFINE_KEY(layout_option)
DEFINE_KEY(swap_screen)
DEFINE_KEY(upright_screen)
DEFINE_KEY(secondary_display_layout)
DEFINE_KEY(large_screen_proportion)
DEFINE_KEY(screen_gap)
DEFINE_KEY(small_screen_position)
DEFINE_KEY(custom_top_x)
DEFINE_KEY(custom_top_y)
DEFINE_KEY(custom_top_width)
DEFINE_KEY(custom_top_height)
DEFINE_KEY(custom_bottom_x)
DEFINE_KEY(custom_bottom_y)
DEFINE_KEY(custom_bottom_width)
DEFINE_KEY(custom_bottom_height)
DEFINE_KEY(custom_second_layer_opacity)
DEFINE_KEY(aspect_ratio)
DEFINE_KEY(screen_top_stretch)
DEFINE_KEY(screen_top_leftright_padding)
DEFINE_KEY(screen_top_topbottom_padding)
DEFINE_KEY(screen_bottom_stretch)
DEFINE_KEY(screen_bottom_leftright_padding)
DEFINE_KEY(screen_bottom_topbottom_padding)
DEFINE_KEY(portrait_layout_option)
DEFINE_KEY(custom_portrait_top_x)
DEFINE_KEY(custom_portrait_top_y)
DEFINE_KEY(custom_portrait_top_width)
DEFINE_KEY(custom_portrait_top_height)
DEFINE_KEY(custom_portrait_bottom_x)
DEFINE_KEY(custom_portrait_bottom_y)
DEFINE_KEY(custom_portrait_bottom_width)
DEFINE_KEY(custom_portrait_bottom_height)
DEFINE_KEY(bg_red)
DEFINE_KEY(bg_green)
DEFINE_KEY(bg_blue)
DEFINE_KEY(render_3d)
DEFINE_KEY(factor_3d)
DEFINE_KEY(swap_eyes_3d)
DEFINE_KEY(render_3d_which_display)
DEFINE_KEY(mono_render_option)
DEFINE_KEY(cardboard_screen_size)
DEFINE_KEY(cardboard_x_shift)
DEFINE_KEY(cardboard_y_shift)
DEFINE_KEY(filter_mode)
DEFINE_KEY(pp_shader_name)
DEFINE_KEY(anaglyph_shader_name)
DEFINE_KEY(dump_textures)
DEFINE_KEY(custom_textures)
DEFINE_KEY(preload_textures)
DEFINE_KEY(async_custom_loading)
DEFINE_KEY(disable_right_eye_render)
DEFINE_KEY(audio_emulation)
DEFINE_KEY(enable_audio_stretching)
DEFINE_KEY(enable_realtime_audio)
DEFINE_KEY(volume)
DEFINE_KEY(output_type)
DEFINE_KEY(output_device)
DEFINE_KEY(input_type)
DEFINE_KEY(input_device)
DEFINE_KEY(simulate_headphones_plugged)
DEFINE_KEY(delay_start_for_lle_modules)
DEFINE_KEY(use_gdbstub)
DEFINE_KEY(gdbstub_port)
DEFINE_KEY(instant_debug_log)
DEFINE_KEY(enable_rpc_server)
DEFINE_KEY(log_filter)
DEFINE_KEY(log_regex_filter)
DEFINE_KEY(toggle_unique_data_console_type)
DEFINE_KEY(break_on_unmapped_memory_access)
DEFINE_KEY(use_integer_scaling)
DEFINE_KEY(layouts_to_cycle)
DEFINE_KEY(camera_inner_flip)
DEFINE_KEY(camera_outer_left_flip)
DEFINE_KEY(camera_outer_right_flip)
DEFINE_KEY(camera_inner_name)
DEFINE_KEY(camera_inner_config)
DEFINE_KEY(camera_outer_left_name)
DEFINE_KEY(camera_outer_left_config)
DEFINE_KEY(camera_outer_right_name)
DEFINE_KEY(camera_outer_right_config)
DEFINE_KEY(video_encoder)
DEFINE_KEY(video_encoder_options)
DEFINE_KEY(video_bitrate)
DEFINE_KEY(audio_encoder)
DEFINE_KEY(audio_encoder_options)
DEFINE_KEY(audio_bitrate)
DEFINE_KEY(last_artic_base_addr)
DEFINE_KEY(motion_device)
DEFINE_KEY(touch_device)
DEFINE_KEY(udp_input_address)
DEFINE_KEY(udp_input_port)
DEFINE_KEY(udp_pad_index)
DEFINE_KEY(record_frame_times)
DEFINE_KEY(language)
DEFINE_KEY(web_api_url)
DEFINE_KEY(citra_username)
DEFINE_KEY(citra_token)
DEFINE_KEY(nickname)
DEFINE_KEY(ip)
DEFINE_KEY(port)
DEFINE_KEY(room_nickname)
DEFINE_KEY(room_name)
DEFINE_KEY(room_port)
DEFINE_KEY(host_type)
DEFINE_KEY(max_player)
DEFINE_KEY(room_description)
DEFINE_KEY(multiplayer_filter_text)
DEFINE_KEY(multiplayer_filter_games_owned)
DEFINE_KEY(multiplayer_filter_hide_empty)
DEFINE_KEY(multiplayer_filter_hide_full)
DEFINE_KEY(username_ban_list)
DEFINE_KEY(username)
DEFINE_KEY(ip_ban_list)
DEFINE_KEY(romsPath)
DEFINE_KEY(symbolsPath)
DEFINE_KEY(movieRecordPath)
DEFINE_KEY(moviePlaybackPath)
DEFINE_KEY(videoDumpingPath)
DEFINE_KEY(gameListRootDir)
DEFINE_KEY(gameListDeepScan)
DEFINE_KEY(path)
DEFINE_KEY(deep_scan)
DEFINE_KEY(expanded)
DEFINE_KEY(recentFiles)
DEFINE_KEY(output_format)
DEFINE_KEY(format_options)
DEFINE_KEY(theme)
DEFINE_KEY(program_id)
DEFINE_KEY(geometry)
DEFINE_KEY(state)
DEFINE_KEY(geometryRenderWindow)
DEFINE_KEY(gameListHeaderState)
DEFINE_KEY(microProfileDialogGeometry)
DEFINE_KEY(name)
DEFINE_KEY(bind)
DEFINE_KEY(profile)
DEFINE_KEY(use_touchpad)
DEFINE_KEY(controller_touch_device)
DEFINE_KEY(use_touch_from_button)
DEFINE_KEY(touch_from_button_map)
DEFINE_KEY(touch_from_button_maps)
DEFINE_KEY(nand_directory)
DEFINE_KEY(sdmc_directory)
DEFINE_KEY(game_id)
DEFINE_KEY(KeySeq)
DEFINE_KEY(gamedirs)
DEFINE_KEY(libvorbis)
DEFINE_KEY(Context)
DEFINE_KEY(favorites)

static const std::array keys_array = {

"use_artic_base_controller",
"enable_gamemode",
"use_cpu_jit",
"cpu_clock_percentage",
"is_new_3ds",
"lle_applets",
"deterministic_async_operations",
"enable_required_online_lle_modules",
"use_virtual_sd",
"use_custom_storage",
"compress_cia_installs",
"async_fs_operations",
"region_value",
"init_clock",
"init_time",
"init_time_offset",
"init_ticks_type",
"init_ticks_override",
"plugin_loader",
"allow_plugin_loader",
"steps_per_hour",
"apply_region_free_patch",
"graphics_api",
"physical_device",
"use_gles",
"renderer_debug",
"pica_debugging",
"dump_command_buffers",
"spirv_shader_gen",
"disable_spirv_optimizer",
"async_shader_compilation",
"async_presentation",
"use_hw_shader",
"use_disk_shader_cache",
"shaders_accurate_mul",
"use_vsync",
"use_skip_duplicate_frames",
"use_display_refresh_rate_detection",
"use_shader_jit",
"resolution_factor",
"frame_limit",
"turbo_limit",
"texture_filter",
"texture_sampling",
"delay_game_render_thread_us",
"simulate_3ds_gpu_timings",
"layout_option",
"swap_screen",
"upright_screen",
"secondary_display_layout",
"large_screen_proportion",
"screen_gap",
"small_screen_position",
"custom_top_x",
"custom_top_y",
"custom_top_width",
"custom_top_height",
"custom_bottom_x",
"custom_bottom_y",
"custom_bottom_width",
"custom_bottom_height",
"custom_second_layer_opacity",
"aspect_ratio",
"screen_top_stretch",
"screen_top_leftright_padding",
"screen_top_topbottom_padding",
"screen_bottom_stretch",
"screen_bottom_leftright_padding",
"screen_bottom_topbottom_padding",
"portrait_layout_option",
"custom_portrait_top_x",
"custom_portrait_top_y",
"custom_portrait_top_width",
"custom_portrait_top_height",
"custom_portrait_bottom_x",
"custom_portrait_bottom_y",
"custom_portrait_bottom_width",
"custom_portrait_bottom_height",
"bg_red",
"bg_green",
"bg_blue",
"render_3d",
"factor_3d",
"swap_eyes_3d",
"render_3d_which_display",
"mono_render_option",
"cardboard_screen_size",
"cardboard_x_shift",
"cardboard_y_shift",
"filter_mode",
"pp_shader_name",
"anaglyph_shader_name",
"dump_textures",
"custom_textures",
"preload_textures",
"async_custom_loading",
"disable_right_eye_render",
"audio_emulation",
"enable_audio_stretching",
"enable_realtime_audio",
"volume",
"output_type",
"output_device",
"input_type",
"input_device",
"simulate_headphones_plugged",
"delay_start_for_lle_modules",
"use_gdbstub",
"gdbstub_port",
"instant_debug_log",
"enable_rpc_server",
"log_filter",
"log_regex_filter",
"toggle_unique_data_console_type",
"break_on_unmapped_memory_access",
"use_integer_scaling",
"layouts_to_cycle",
"camera_inner_flip",
"camera_outer_left_flip",
"camera_outer_right_flip",
"camera_inner_name",
"camera_inner_config",
"camera_outer_left_name",
"camera_outer_left_config",
"camera_outer_right_name",
"camera_outer_right_config",
"video_encoder",
"video_encoder_options",
"video_bitrate",
"audio_encoder",
"audio_encoder_options",
"audio_bitrate",
"last_artic_base_addr",
"motion_device",
"touch_device",
"udp_input_address",
"udp_input_port",
"udp_pad_index",
"record_frame_times",
"language",
"web_api_url",
"citra_username",
"citra_token",
"nickname",
"ip",
"port",
"room_nickname",
"room_name",
"room_port",
"host_type",
"max_player",
"room_description",
"multiplayer_filter_text",
"multiplayer_filter_games_owned",
"multiplayer_filter_hide_empty",
"multiplayer_filter_hide_full",
"username_ban_list",
"username",
"ip_ban_list",
"romsPath",
"symbolsPath",
"movieRecordPath",
"moviePlaybackPath",
"videoDumpingPath",
"gameListRootDir",
"gameListDeepScan",
"path",
"deep_scan",
"expanded",
"recentFiles",
"output_format",
"format_options",
"theme",
"program_id",
"geometry",
"state",
"geometryRenderWindow",
"gameListHeaderState",
"microProfileDialogGeometry",
"name",
"bind",
"profile",
"use_touchpad",
"controller_touch_device",
"use_touch_from_button",
"touch_from_button_map",
"touch_from_button_maps",
"nand_directory",
"sdmc_directory",
"game_id",
"KeySeq",
"gamedirs",
"libvorbis",
"Context",
"favorites"
};

#undef DEFINE_KEY
}

namespace HKeys {
#define DEFINE_KEY(KEY) static constexpr auto KEY = BOOST_HANA_STRING(#KEY);


DEFINE_KEY(use_artic_base_controller)
DEFINE_KEY(enable_gamemode)
DEFINE_KEY(use_cpu_jit)
DEFINE_KEY(cpu_clock_percentage)
DEFINE_KEY(is_new_3ds)
DEFINE_KEY(lle_applets)
DEFINE_KEY(deterministic_async_operations)
DEFINE_KEY(enable_required_online_lle_modules)
DEFINE_KEY(use_virtual_sd)
DEFINE_KEY(use_custom_storage)
DEFINE_KEY(compress_cia_installs)
DEFINE_KEY(async_fs_operations)
DEFINE_KEY(region_value)
DEFINE_KEY(init_clock)
DEFINE_KEY(init_time)
DEFINE_KEY(init_time_offset)
DEFINE_KEY(init_ticks_type)
DEFINE_KEY(init_ticks_override)
DEFINE_KEY(plugin_loader)
DEFINE_KEY(allow_plugin_loader)
DEFINE_KEY(steps_per_hour)
DEFINE_KEY(apply_region_free_patch)
DEFINE_KEY(graphics_api)
DEFINE_KEY(physical_device)
DEFINE_KEY(use_gles)
DEFINE_KEY(renderer_debug)
DEFINE_KEY(pica_debugging)
DEFINE_KEY(dump_command_buffers)
DEFINE_KEY(spirv_shader_gen)
DEFINE_KEY(disable_spirv_optimizer)
DEFINE_KEY(async_shader_compilation)
DEFINE_KEY(async_presentation)
DEFINE_KEY(use_hw_shader)
DEFINE_KEY(use_disk_shader_cache)
DEFINE_KEY(shaders_accurate_mul)
DEFINE_KEY(use_vsync)
DEFINE_KEY(use_skip_duplicate_frames)
DEFINE_KEY(use_display_refresh_rate_detection)
DEFINE_KEY(use_shader_jit)
DEFINE_KEY(resolution_factor)
DEFINE_KEY(frame_limit)
DEFINE_KEY(turbo_limit)
DEFINE_KEY(texture_filter)
DEFINE_KEY(texture_sampling)
DEFINE_KEY(delay_game_render_thread_us)
DEFINE_KEY(simulate_3ds_gpu_timings)
DEFINE_KEY(layout_option)
DEFINE_KEY(swap_screen)
DEFINE_KEY(upright_screen)
DEFINE_KEY(secondary_display_layout)
DEFINE_KEY(large_screen_proportion)
DEFINE_KEY(screen_gap)
DEFINE_KEY(small_screen_position)
DEFINE_KEY(custom_top_x)
DEFINE_KEY(custom_top_y)
DEFINE_KEY(custom_top_width)
DEFINE_KEY(custom_top_height)
DEFINE_KEY(custom_bottom_x)
DEFINE_KEY(custom_bottom_y)
DEFINE_KEY(custom_bottom_width)
DEFINE_KEY(custom_bottom_height)
DEFINE_KEY(custom_second_layer_opacity)
DEFINE_KEY(aspect_ratio)
DEFINE_KEY(screen_top_stretch)
DEFINE_KEY(screen_top_leftright_padding)
DEFINE_KEY(screen_top_topbottom_padding)
DEFINE_KEY(screen_bottom_stretch)
DEFINE_KEY(screen_bottom_leftright_padding)
DEFINE_KEY(screen_bottom_topbottom_padding)
DEFINE_KEY(portrait_layout_option)
DEFINE_KEY(custom_portrait_top_x)
DEFINE_KEY(custom_portrait_top_y)
DEFINE_KEY(custom_portrait_top_width)
DEFINE_KEY(custom_portrait_top_height)
DEFINE_KEY(custom_portrait_bottom_x)
DEFINE_KEY(custom_portrait_bottom_y)
DEFINE_KEY(custom_portrait_bottom_width)
DEFINE_KEY(custom_portrait_bottom_height)
DEFINE_KEY(bg_red)
DEFINE_KEY(bg_green)
DEFINE_KEY(bg_blue)
DEFINE_KEY(render_3d)
DEFINE_KEY(factor_3d)
DEFINE_KEY(swap_eyes_3d)
DEFINE_KEY(render_3d_which_display)
DEFINE_KEY(mono_render_option)
DEFINE_KEY(cardboard_screen_size)
DEFINE_KEY(cardboard_x_shift)
DEFINE_KEY(cardboard_y_shift)
DEFINE_KEY(filter_mode)
DEFINE_KEY(pp_shader_name)
DEFINE_KEY(anaglyph_shader_name)
DEFINE_KEY(dump_textures)
DEFINE_KEY(custom_textures)
DEFINE_KEY(preload_textures)
DEFINE_KEY(async_custom_loading)
DEFINE_KEY(disable_right_eye_render)
DEFINE_KEY(audio_emulation)
DEFINE_KEY(enable_audio_stretching)
DEFINE_KEY(enable_realtime_audio)
DEFINE_KEY(volume)
DEFINE_KEY(output_type)
DEFINE_KEY(output_device)
DEFINE_KEY(input_type)
DEFINE_KEY(input_device)
DEFINE_KEY(simulate_headphones_plugged)
DEFINE_KEY(delay_start_for_lle_modules)
DEFINE_KEY(use_gdbstub)
DEFINE_KEY(gdbstub_port)
DEFINE_KEY(instant_debug_log)
DEFINE_KEY(enable_rpc_server)
DEFINE_KEY(log_filter)
DEFINE_KEY(log_regex_filter)
DEFINE_KEY(toggle_unique_data_console_type)
DEFINE_KEY(break_on_unmapped_memory_access)
DEFINE_KEY(use_integer_scaling)
DEFINE_KEY(layouts_to_cycle)
DEFINE_KEY(camera_inner_flip)
DEFINE_KEY(camera_outer_left_flip)
DEFINE_KEY(camera_outer_right_flip)
DEFINE_KEY(camera_inner_name)
DEFINE_KEY(camera_inner_config)
DEFINE_KEY(camera_outer_left_name)
DEFINE_KEY(camera_outer_left_config)
DEFINE_KEY(camera_outer_right_name)
DEFINE_KEY(camera_outer_right_config)
DEFINE_KEY(video_encoder)
DEFINE_KEY(video_encoder_options)
DEFINE_KEY(video_bitrate)
DEFINE_KEY(audio_encoder)
DEFINE_KEY(audio_encoder_options)
DEFINE_KEY(audio_bitrate)
DEFINE_KEY(last_artic_base_addr)
DEFINE_KEY(motion_device)
DEFINE_KEY(touch_device)
DEFINE_KEY(udp_input_address)
DEFINE_KEY(udp_input_port)
DEFINE_KEY(udp_pad_index)
DEFINE_KEY(record_frame_times)
DEFINE_KEY(language)
DEFINE_KEY(web_api_url)
DEFINE_KEY(citra_username)
DEFINE_KEY(citra_token)
DEFINE_KEY(nickname)
DEFINE_KEY(ip)
DEFINE_KEY(port)
DEFINE_KEY(room_nickname)
DEFINE_KEY(room_name)
DEFINE_KEY(room_port)
DEFINE_KEY(host_type)
DEFINE_KEY(max_player)
DEFINE_KEY(room_description)
DEFINE_KEY(multiplayer_filter_text)
DEFINE_KEY(multiplayer_filter_games_owned)
DEFINE_KEY(multiplayer_filter_hide_empty)
DEFINE_KEY(multiplayer_filter_hide_full)
DEFINE_KEY(username_ban_list)
DEFINE_KEY(username)
DEFINE_KEY(ip_ban_list)
DEFINE_KEY(romsPath)
DEFINE_KEY(symbolsPath)
DEFINE_KEY(movieRecordPath)
DEFINE_KEY(moviePlaybackPath)
DEFINE_KEY(videoDumpingPath)
DEFINE_KEY(gameListRootDir)
DEFINE_KEY(gameListDeepScan)
DEFINE_KEY(path)
DEFINE_KEY(deep_scan)
DEFINE_KEY(expanded)
DEFINE_KEY(recentFiles)
DEFINE_KEY(output_format)
DEFINE_KEY(format_options)
DEFINE_KEY(theme)
DEFINE_KEY(program_id)
DEFINE_KEY(geometry)
DEFINE_KEY(state)
DEFINE_KEY(geometryRenderWindow)
DEFINE_KEY(gameListHeaderState)
DEFINE_KEY(microProfileDialogGeometry)
DEFINE_KEY(name)
DEFINE_KEY(bind)
DEFINE_KEY(profile)
DEFINE_KEY(use_touchpad)
DEFINE_KEY(controller_touch_device)
DEFINE_KEY(use_touch_from_button)
DEFINE_KEY(touch_from_button_map)
DEFINE_KEY(touch_from_button_maps)
DEFINE_KEY(nand_directory)
DEFINE_KEY(sdmc_directory)
DEFINE_KEY(game_id)
DEFINE_KEY(KeySeq)
DEFINE_KEY(gamedirs)
DEFINE_KEY(libvorbis)
DEFINE_KEY(Context)
DEFINE_KEY(favorites)

#undef DEFINE_KEY
}

}
